# -*- coding: utf-8 -*-
"""html_quick_styler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-O_c0YNljb3W2klX7jcQI_Ba7chhbaF
"""

!pip install gradio transformers torch

import gradio as gr

# -------------------------------
# HTML GENERATOR
# -------------------------------

def generate_html(title, desc, style):

    html = f"""
    <html>
    <head>
    <style>
    body {{
        font-family: Arial;
        background:#0f172a;
        color:white;
        margin:0;
    }}

    nav {{
        background:#1e293b;
        padding:15px;
        display:flex;
        justify-content:space-between;
    }}

    .hero {{
        height:300px;
        display:flex;
        flex-direction:column;
        justify-content:center;
        align-items:center;
        background:linear-gradient(90deg,#6366f1,#8b5cf6);
    }}

    button {{
        padding:10px 20px;
        border:none;
        background:#f97316;
        color:white;
        border-radius:5px;
    }}

    </style>
    </head>

    <body>

    <nav>
    <h3>{title}</h3>
    <div>Features &nbsp;&nbsp; About &nbsp;&nbsp; Contact</div>
    </nav>

    <div class="hero">
    <h1>Welcome to Your Site</h1>
    <p>Create amazing web experiences</p>
    <button>Get Started</button>
    </div>

    </body>
    </html>
    """

    return html, html

# ----------------
# Live Preview
# ----------------

with gr.Tab("Live Preview"):

     preview = gr.HTML()


# -------------------------------
# COLOR PALETTE
# -------------------------------

def show_palette(style):

    palettes = {
        "modern": ["#6366f1","#7c3aed","#0f172a","#f1f5f9"],
        "vibrant": ["#f97316","#ef4444","#1e293b","#f9fafb"],
        "ocean": ["#0284c7","#0ea5e9","#0f172a","#e0f2fe"],
        "forest": ["#16a34a","#4ade80","#052e16","#ecfdf5"],
        "sunset": ["#f97316","#fb7185","#431407","#fff7ed"],
        "luxury": ["#c9a227","#e5e4e2","#111","#fff"],
        "creative": ["#8b5cf6","#ec4899","#1e1b4b","#faf5ff"],
        "minimal": ["#000","#6b7280","#fff","#111"]
    }

    colors = palettes.get(style)

    html = "<h3>Palette for "+style+"</h3>"

    for c in colors:
        html += f"""
        <div style="background:{c};height:50px;margin:10px;border-radius:6px;"></div>
        """

    return html


# -------------------------------
# TEMPLATE SELECTOR
# -------------------------------

def use_template(name):

    templates = {
        "Portfolio Website":
        "Hero, Portfolio Gallery, About, Contact, Footer",

        "SaaS Landing Page":
        "Hero, Features, Pricing, Testimonials, CTA, Footer",

        "Company Website":
        "Header, About, Services, Team, Contact, Footer"
    }

    return templates.get(name)


# -------------------------------
# GUIDE
# -------------------------------

def show_guide():

    return """
    <h2>HTML Quick-Styler Guide</h2>

    <h3>1. Enter Details</h3>
    Title, description and color style.

    <h3>2. Automatic Detection</h3>

    hero → hero section
    features → feature grid
    about → about section
    portfolio → gallery
    testimonials → testimonials
    pricing → pricing plans
    contact → contact form
    footer → footer

    <h3>3. Generate & Customize</h3>

    Click Generate HTML
    Preview your site instantly.
    """


# -------------------------------
# INTERFACE
# -------------------------------

with gr.Blocks() as app:

    gr.Markdown("# 🧠 HTML Quick-Styler Advanced")
    gr.Markdown("Professional HTML Page Generator with Auto-Styling")

    with gr.Tabs():

        # PAGE 1
        with gr.Tab("Generate Page"):

            with gr.Row():

                with gr.Column():

                    gr.Markdown("### Page Details")

                    title = gr.Textbox(value="Modern Portfolio Website")

                    desc = gr.Textbox(
                        lines=4,
                        value="Hero section with welcome message, features list with 3 items"
                    )

                    style = gr.Dropdown(
                        ["modern","vibrant","ocean","forest","sunset","luxury","creative","minimal"],
                        value="modern"
                    )

                    btn = gr.Button("Generate HTML")

                with gr.Column():

                    gr.Markdown("### Output")

                    code = gr.Code(language="html")

        # PAGE 2
        with gr.Tab("Live Preview"):

            preview_btn = gr.Button("Load Preview")

            preview = gr.HTML()

        # PAGE 3
        with gr.Tab("Color Palettes"):

            palette_style = gr.Radio(
                ["modern","vibrant","ocean","forest","sunset","luxury","creative","minimal"],
                value="modern"
            )

            palette_btn = gr.Button("Get Palette")

            palette_display = gr.HTML()

        # PAGE 4
        with gr.Tab("Templates"):

            template = gr.Radio(
                ["Portfolio Website","SaaS Landing Page","Company Website"]
            )

            template_btn = gr.Button("Use Template")

            template_output = gr.Textbox()

        # PAGE 5
        with gr.Tab("Guide"):

            guide_btn = gr.Button("Show Guide")

            guide = gr.HTML()

    # FUNCTIONS

    btn.click(generate_html,[title,desc,style],[code,preview])

    preview_btn.click(generate_html,[title,desc,style],[code,preview])

    palette_btn.click(show_palette,palette_style,palette_display)

    template_btn.click(use_template,template,template_output)

    guide_btn.click(show_guide,None,guide)

app.launch()